// generated by Fast Light User Interface Designer (fluid) version 1.0404

#include "dupdetectwindow.hpp"
#include <FL/Enumerations.H>
#include <FL/fl_ask.H>
#include <FL/Fl_Text_Display.H>
#include <FL/Fl_Tree.H>
#include <FL/Fl_Tree_Item.H>
#include <FL/Fl_Widget.H>
#include <FL/Fl_Window.H>

#include <algorithm>
#include <atomic>
#include <cassert>
#include <cstddef>
#include <cstring>
#include <format>
#include <iostream>
#include <memory>
#include <stdexcept>
#include <string>
#include <thread>
#include <unordered_set>
#include <utility>
#include "FL/Fl_Native_File_Chooser.H"

#include "confirm.hpp"
#include "directoryhasher.hpp"
#include "file-platform.hpp"
#include "scwindow.hpp"
#include "uiupdate.hpp"
#include "utils.hpp"

/**
 * self is the window to be centered or the whole screen if parent is nullptr
 * parent: The window self will be centered relative to. Optional
 * w: the width of the self
 * h: the height of self
 */
auto center(Fl_Window* self, Fl_Window* parent, int w, int h) -> Fl_Window*
{
    auto max_x = parent == nullptr ? Fl::w() : parent->w();
    auto max_y = parent == nullptr ? Fl::h() : parent->h();

    auto px = parent == nullptr ? 0 : parent->x();
    auto py = parent == nullptr ? 0 : parent->y();

    auto x = px + (max_x / 2) - (w / 2);
    auto y = py + (max_y / 2) - (h / 2);

    assert(x > 0);
    assert(x < Fl::w());
    assert(y > 0);
    assert(y < Fl::h());

    self->resize(x, y, w, h);
    return self;
}

/**
 * self is the window to be centered
 * parent is optional. self will be centered relative to the parent or the whole
 * screen if parent is nullptr
 */
auto center(Fl_Window* self, Fl_Window* parent) -> Fl_Window*
{
    return center(self, parent, self->w(), self->h());
}

auto center(Fl_Window* self) -> Fl_Window*
{
    return center(self, nullptr, self->w(), self->h());
}

static void relabel_hash_parent(Fl_Tree_Item* item)
{
    if (!item || !item->label()) {
        ::output("Unexpected null item! Application will terminate!");
        die();
    }
    // re-make the label for this hash to reflect the removed files
    std::string label = item->label();
    auto        pos   = std::find(label.begin(), label.end(), '(');
    if (pos == label.end()) {
        ::output(
            "Hash parent relabel does not match expected string. Application "
            "will terminate!");
        die();
    }
    label.erase(pos, label.end());
    label.insert(label.size(), std::format("({} files)", item->children()));
    // FLTK's Fl_Tree_Item::label() copies the string internally
    item->label(label.c_str());
}

std::shared_ptr<DupDetectWindow> DupDetectWindow::construct_window()
{
    auto w = std::shared_ptr<DupDetectWindow>{new DupDetectWindow(770, 580)};
    w->box(FL_FLAT_BOX);
    w->color(FL_BACKGROUND_COLOR);
    w->selection_color(FL_BACKGROUND_COLOR);
    w->labeltype(FL_NO_LABEL);
    w->labelfont(0);
    w->labelsize(14);
    w->labelcolor(FL_FOREGROUND_COLOR);
    w->align(Fl_Align(FL_ALIGN_TOP));
    w->when(FL_WHEN_RELEASE);
    {
        Fl_Button* o = new Fl_Button(15, 15, 132, 28, "Choose Directory");
        o->tooltip("Choose a directory to scan for duplicates");
        o->selection_color((Fl_Color) 48);
        o->align(Fl_Align(FL_ALIGN_WRAP));
        w->My_selectDirButton = o;
    }  // Fl_Button* o
    {
        Fl_Output* o = new Fl_Output(229, 15, 443, 28, "Directory:");
        o->color((Fl_Color) 48);
        w->My_selectedDirOutput = o;
    }  // Fl_Output* o
    {
        w->My_startScanButton = new Fl_Button(685, 15, 70, 28, "Scan");
        w->My_startScanButton->tooltip("Start scanning for duplicates");
        w->My_startScanButton->align(Fl_Align(FL_ALIGN_WRAP));
        w->My_startScanButton->deactivate();
    }  // Fl_Button* o
    {
        w->My_scanProgressBar =
            new Fl_Progress(15, 105, 740, 25, "Scan Progress");
        w->My_scanProgressBar->minimum(0);
        w->My_scanProgressBar->maximum(100);
    }  // Fl_Progress* o
    {
#ifdef __APPLE__
        // macOS allows us to call fl_width with no window, but linux does
        // not;
        auto text_width = fl_width("Currently Hashing:") + 5;
#else
        auto text_width = 175;
#endif
        Fl_Output* o = new Fl_Output(text_width + 17, 60, 740 - 2 - text_width,
                                     28, "Currently Hashing:");
        o->color((Fl_Color) 48);
        w->My_currentTargetFile = o;
    }  // Fl_Output* o
    {
        Fl_Output* o = new Fl_Output(20, 150, 740, 28);
        o->box(FL_NO_BOX);
        o->color(FL_GRAY);
        o->value(
            "Click a hash to delete all matching duplicates except the "
            "blue one. Click ANY file to delete it directly.");
    }
    {
        w->My_resultsTree = new Fl_Tree(15, 180, 740, 340);
        w->resizable(w->My_resultsTree);
    }  // Fl_Tree* o
    {
        w->My_deleteItemButton = new Fl_Button(15, 530, 132, 28, "Delete");
        w->My_deleteItemButton->deactivate();
    }
    {
        w->My_removeItemButton = new Fl_Button(157, 530, 132, 28, "Ignore");
        w->My_removeItemButton->deactivate();
    }
    {
        w->My_showItemButton = new Fl_Button(300, 530, 132, 28, "Reveal Item");
        w->My_showItemButton->deactivate();
    }
    w->end();
    return w;
}  // DupDetectWindow* o

DupDetectWindow::DupDetectWindow(int w, int h)
    : Fl_Window(w, h), survivor_strategy()
{
    center(this);
}

DupDetectWindow::~DupDetectWindow() noexcept
{
    // Signal the scanning thread to stop
    scanning.store(false, std::memory_order_release);

    // Wait for the scanning thread to finish if it's running
    if (scan_thread_.has_value() && scan_thread_->joinable()) {
        scan_thread_->join();
    }
}

void DupDetectWindow::perform_choose_dir()
{
    Fl_Native_File_Chooser fc;
    fc.title("Select Directory to Scan");
    fc.type(Fl_Native_File_Chooser::BROWSE_DIRECTORY);
    fc.show();
    auto filename = fc.filename();
    My_selectedDirOutput->value(filename);
    if (filename && *filename) {
        My_startScanButton->activate();
    } else {
        My_startScanButton->deactivate();
    }
}

void DupDetectWindow::send_progress(std::shared_ptr<DupDetectWindow> window,
                                    std::size_t                      progress,
                                    std::size_t                      total,
                                    std::string const&               message)
{
    assert(window != nullptr);
    // this will be freed in the callback function
    UIUpdate* update = new UIUpdate();
    update->message  = message;
    update->window   = window;
    update->progress = progress;
    update->total    = total;
    update->type     = UIUpdate::Type::Progress;
    Fl::awake(ui_scan_update_cb, update);
}

void DupDetectWindow::send_done(std::shared_ptr<DupDetectWindow> window,
                                std::size_t                      progress,
                                std::size_t                      total,
                                std::string const&               message,
                                std::shared_ptr<DuplicateFilesCollection> files)
{
    assert(window != nullptr);
    // this will be freed in the callback function
    UIUpdate* update   = new UIUpdate();
    update->duplicates = files;
    update->message    = message;
    update->window     = window;
    update->progress   = progress;
    update->total      = total;
    update->type       = UIUpdate::Type::Done;
    window->scanning.store(false, std::memory_order_release);
    Fl::awake(ui_scan_update_cb, update);
}

void DupDetectWindow::perform_start_scan()
{
    std::string selectedDir = My_selectedDirOutput->value();
    if (selectedDir.empty()) {
        std::cout << "No directory selected." << std::endl;
        fl_alert("No directory chosen!");
        return;
    }

    if (scanning.load(std::memory_order_acquire)) {
        // if we are scanning and we click this button
        // we should cancel the scan and update the UI
        display_not_scanning();
        scanning.store(false, std::memory_order_release);

        // Wait for the scanning thread to finish
        if (scan_thread_.has_value() && scan_thread_->joinable()) {
            scan_thread_->join();
        }
        return;
    } else {
        // Join any previous scan thread before starting a new one
        if (scan_thread_.has_value() && scan_thread_->joinable()) {
            scan_thread_->join();
        }

        // clear the old results
        My_resultsTree->clear();
        Fl::check();

        // if we are not scanning we will ask for a strategy
        // update the ui and spawn a thread to start the scan
        scanning.store(true, std::memory_order_release);
        if (!ask_for_choice()) {
            return;
        }

        My_removeItemButton->deactivate();
        My_deleteItemButton->deactivate();
        My_showItemButton->deactivate();
        My_startScanButton->label("Cancel Scan");
        My_scanProgressBar->label(
            "Preparing for scan. Please wait a moment...");
        My_resultsTree->clear();
        std::thread t{[win_weak = std::weak_ptr<DupDetectWindow>(
                           this->shared_from_this()),
                       selectedDir]() {
            // Try to lock the weak_ptr to get a shared_ptr
            auto win = win_weak.lock();
            if (!win) {
                return;  // Window was destroyed
            }

            std::unique_ptr<DirectoryHasher> hasher;
            try {
                hasher = std::make_unique<DirectoryHasher>(selectedDir);
            } catch (std::exception& e) {
                auto error_msg = std::format(
                    "Cannot access selected directory for hashing.\n\n"
                    "Error: {}\n\n"
                    "Ensure appropriate permissions or select a new directory.",
                    e.what());
                fl_alert("%s", error_msg.c_str());
                win->send_done(win, 0, 0, "ERROR: " + std::string(e.what()),
                               std::shared_ptr<DuplicateFilesCollection>{});
                return;  // Exit early if hasher construction failed
            }
            std::atomic<bool> update_ready{false};

            std::thread pt{[&hasher, win_weak, &update_ready]() {
                while (true) {
                    auto win = win_weak.lock();
                    if (!win ||
                        !win->scanning.load(std::memory_order_acquire)) {
                        break;  // Window destroyed or scanning stopped
                    }

                    std::this_thread::sleep_for(ui_update_delay);
                    if (update_ready.load()) {
                        win->send_progress(
                            win, hasher->get_progress(), hasher->get_total(),
                            hasher->will_be_hashed().value_or("..."));
                        update_ready.store(false);
                    }
                }
            }};

            std::optional<std::tuple<DirectoryHasher::PathType,
                                     DirectoryHasher::HashType>>
                result;
            do {
                try {
                    result = hasher->next();
                    if (!result.has_value()) {
                        break;
                    }
                    update_ready.store(true);
                    // Check if window still exists and user hasn't cancelled
                    auto win_check = win_weak.lock();
                    if (!win_check ||
                        !win_check->scanning.load(std::memory_order_acquire)) {
                        break;
                    }
                } catch (file_hash_error& err) {
                    fl_alert("Could not compute file hash");
                    continue;
                } catch (...) {
                    fl_alert("Error accessing file");
                    continue;
                }
                debug_output("Hashed: ", std::get<0>(*(result)), " -> ",
                             std::get<1>(*(result)));

            } while (result.has_value());

            // Final check that window still exists before cleanup
            if (auto win_final = win_weak.lock()) {
                DEBUG_USE_ONLY auto unique_hash_count =
                    hasher->duplicates->size();
                win_final->send_done(win_final, hasher->get_progress(),
                                     hasher->get_total(), "<none>",
                                     std::move(hasher->duplicates));
                debug_output("Hashing complete. Unique hashes found: ",
                             unique_hash_count);
            }

            // pt must be joined after send_done because send_done sets scanning
            // to false, breaking out of the pt loop
            pt.join();
        }};

        // Store the thread instead of detaching it
        scan_thread_ = std::move(t);
    }
}

static Fl_Tree_Item* try_get_selected_item(Fl_Tree* tree)
{
    auto* item = tree->first_selected_item();
    if (item == nullptr) {
        fl_alert("No selection");
        return nullptr;
    }

    if (item == tree->root()) {
        fl_alert(
            "Cannot delete the root element. Choose a hash or an "
            "individual file");
        return nullptr;
    }
    return item;
}

void DupDetectWindow::perform_show_item()
{
    auto* item = My_resultsTree->first_selected_item();

    if (item == nullptr) {
        fl_alert("No selection!");
        return;
    }

    if (item->user_data() == parent_sentinel ||
        item == My_resultsTree->root()) {
        fl_alert("Select a single file to reveal it");
        return;
    }

    reveal_file(item->label());
}

void DupDetectWindow::perform_delete_item()
{
    Fl_Tree_Item* item = try_get_selected_item(My_resultsTree);
    if (item == nullptr) {
        return;
    }

    // check != parent_sentintel bc a child can have nullptr OR
    // survivor_sentinel for user_data
    if (item->user_data() != parent_sentinel) {
        // delete a single file
        // ask for confirmation
        auto result =
            confirm("Are you sure you want to delete %s.", item->label());
        if (result != ConfirmResult::YES) {
            return;
        }
        // this is a specific file that the user chose to delete
        ::output("Deleting specific file ", item->label());

        delete_single_item(item);
    } else {
        // Delete all duplicates
        // confirm with the user first
        auto child_count = item->children();
        if (child_count == 0) {
            fl_alert("Nothing to delete!");
            return;
        }

        if (child_count == 1) {
            fl_alert(
                "There exists ONLY ONE file matching this hash left. "
                "To delete it, select it and delete it explicitly");
            return;
        }

        auto result = confirm(
            "Warning you are about to delete %d files. ALL "
            "files under this hash except the newest will be "
            "deleted. Do you want to continue?",
            child_count - 1);

        if (result != ConfirmResult::YES) {
            return;
        }

        ::output("Will delete all duplicates except designated survivor");
        delete_hash_parent_item(item, child_count);
    }
    // TODO: why does the UI not refresh even if I call Fl::check();
}

void DupDetectWindow::perform_remove_item()
{
    auto*               item = My_resultsTree->first_selected_item();
    static ConfirmToken remove_token{};

    if (item == nullptr) {
        fl_alert("No selection!");
        return;
    }

    if (item->user_data() == parent_sentinel) {
        // we have a parent

        // double check with the user
        auto result = confirm(
            &remove_token, "Are you sure you want to hide %s?", item->label());
        if (result != ConfirmResult::YES) {
            return;
        }

        // lets not show it but not actually do anything
        My_resultsTree->remove(item);
        return;
    }
    fl_alert("Can only ignore hash values. Select a hash to ignore it.");
}

void DupDetectWindow::delete_single_item(Fl_Tree_Item* item)
{
    // Fix parent content to reflect removed file
    auto* parent = item->parent();
    if (parent == nullptr) {
        ::output("Unexpected nullptr parent on ", item->label());
        throw std::runtime_error("unexpected null parent");
    }

    if (item->user_data() == survivor_sentinel && parent->children() > 1) {
        // item is designated survivor, new survivor must be chosen
        // AS LONG AS there are still other files to choose from
        // If this is the last file matching the hash, it can be
        // removed//
        choose_survivor_after_delete(parent, item);
    }

    My_resultsTree->remove(item);
    // TODO: actual file deleting :grimace:

    // if there are files left, reflect that in the count in the
    // parent otherwise remove the empty hash from the view since it
    // is empty
    if (parent->children() > 0) {
        relabel_hash_parent(parent);
    } else {
        My_resultsTree->remove(parent);
    }
}

void DupDetectWindow::delete_hash_parent_item(Fl_Tree_Item* item,
                                              int           child_count)
{
    // find the child with the user data indicating it is
    // the newest and should be saved
    for (auto i = child_count - 1; i >= 0; --i) {
        if (auto* child = item->child(i);
            child && child->user_data() != survivor_sentinel) {
            ::output("Will delete ", child->label());
            My_resultsTree->remove(child);
            // TODO: delete actual files
        }
    }

    relabel_hash_parent(item);
}

bool DupDetectWindow::ask_for_choice()
{
    auto choicer = std::make_unique<SurvivorChoiceWindow>(this);
    center(choicer.get(), this);
    choicer->show_and_wait();

    if (choicer->was_cancelled()) {
        fl_alert("No selection made. Cancelling scan");
        return false;
    }

    survivor_strategy = choicer->get_choice();
    return true;
}

std::string DupDetectWindow::choose_survivor_after_delete(
    Fl_Tree_Item* parent,
    Fl_Tree_Item* old_survivor)
{
    std::vector<std::string> options{};
    for (int i = parent->children() - 1; i >= 0; --i) {
        auto* child = parent->child(i);
        if (child == old_survivor)
            continue;
        options.emplace_back(child->label());
    }

    auto new_survivor = choose_survivor(options);

    auto* new_child_survivor = parent->find_child_item(new_survivor.data());
    if (new_child_survivor == nullptr) {
        fl_alert(
            "Could not find suitable replacement for deleted survivor. Program "
            "will terminate!");
        die();
    }
    new_child_survivor->user_data(survivor_sentinel);
    new_child_survivor->labelfgcolor(FL_BLUE);
    old_survivor->user_data(nullptr);
    return new_survivor;
}

std::string DupDetectWindow::choose_survivor(
    std::vector<std::string> const& files) const
{
    if (files.empty()) {
        std::cerr << "Cannot choose survivor from set of 0 options"
                  << std::endl;
        fl_alert(
            "Cannot choose survivor from 0 options. Program will terminate!");
        die();
    }

    switch (survivor_strategy) {
        case SurvivorChoiceType::RANDOM:
            // simulate randomness for debugging purposes
            return files.front();
        case SurvivorChoiceType::NEWEST:
            return *std::max_element(std::begin(files), std::end(files),
                                     [](auto const& file1, auto const& file2) {
                                         return last_write_time_safe(file1) <
                                                last_write_time_safe(file2);
                                     });
        case SurvivorChoiceType::OLDEST:
            return *std::min_element(std::begin(files), std::end(files),
                                     [](auto const& file1, auto const& file2) {
                                         return last_write_time_safe(file1) <
                                                last_write_time_safe(file2);
                                     });
    }

    fl_alert("Invalid choice. Program will terminate!");
    die();
    // let's hope so anyway
    std::unreachable();
}

void DupDetectWindow::update_table(
    std::shared_ptr<DuplicateFilesCollection> duplicateFiles)
{
    // don't let anything happen while the table is updating
    My_startScanButton->deactivate();
    My_resultsTree->clear();
    My_resultsTree->deactivate();
    debug_output("Updating results table...");
    auto amount = duplicateFiles->size();

    if (amount == 0) {
        ::output("NO DUPLICATES FOUND");
        My_resultsTree->add("No duplicates found!");
        My_startScanButton->activate();
        My_deleteItemButton->deactivate();
        My_removeItemButton->deactivate();
        My_showItemButton->deactivate();
        My_resultsTree->activate();
        return;
    }
    // activate the buttons after the populating of the table
    // so that if it takes long they don't activate until the table is ready

    duplicates = duplicateFiles;
    reset_progress(0, amount);
    My_scanProgressBar->value(amount);
    std::size_t count = 0;
    debug_output("Total unique hashes: ", amount);
    My_scanProgressBar->minimum(0);
    My_scanProgressBar->maximum(amount);
    My_scanProgressBar->label("Updating table...");
    for (const auto& [hash, hash_entry] : *duplicateFiles) {
        auto& files = hash_entry.files;
        debug_output("Processing hash: ", hash, " with ", files.size(),
                     " files.");
        if (hash_entry.get_file_count() > 1) {
            auto text = "Hash: " + hash + " (" + std::to_string(files.size()) +
                        " files)";
            debug_output("Adding tree parent: ", text);
            auto parent = My_resultsTree->add(text.c_str());
            parent->user_data(parent_sentinel);
            auto survivor = choose_survivor(files);
            for (const auto& file : files) {
                auto* item = My_resultsTree->add(parent, file.c_str());
                item->labelfgcolor(FL_GRAY);
            }
            auto* sur = parent->find_child_item(survivor.data());
            sur->user_data(survivor_sentinel);
            sur->labelfgcolor(FL_BLUE);
        }
        My_scanProgressBar->value(++count);
        if (count % 2500 == 0) {
            My_resultsTree->redraw();
            My_scanProgressBar->redraw();
            Fl::check();  // Process pending events to update UI
        }
    }
    debug_output("Results table update complete.");
    display_not_scanning();
    My_showItemButton->activate();
    My_removeItemButton->activate();
    My_deleteItemButton->activate();
    My_startScanButton->activate();
    My_resultsTree->activate();
    My_resultsTree->redraw();
}

void DupDetectWindow::display_not_scanning()
{
    My_startScanButton->label("Scan");
    My_currentTargetFile->value("<none>");
    My_scanProgressBar->value(My_scanProgressBar->maximum());
}

void DupDetectWindow::reset_progress(int min, int max)
{
    My_scanProgressBar->minimum(min);
    My_scanProgressBar->maximum(max);
    My_scanProgressBar->value(min);
}

std::shared_ptr<DupDetectWindow> DupDetectWindow::create()
{
    std::shared_ptr<DupDetectWindow> w = construct_window();

    // Helper to create callback user data with weak_ptr for safe lifetime
    // management
    auto make_callback_data = [&w]() {
        auto  weak = std::make_unique<std::weak_ptr<DupDetectWindow>>(w);
        auto* ptr  = weak.get();
        w->callback_weakptrs_.push_back(std::move(weak));
        return ptr;
    };

    w->My_showItemButton->callback(
        []([[maybe_unused]] auto* widget, auto* user_data) {
            auto* weak_ptr =
                static_cast<std::weak_ptr<DupDetectWindow>*>(user_data);
            if (auto ui = weak_ptr->lock()) {
                ui->perform_show_item();
            }
        },
        make_callback_data());

    w->My_removeItemButton->callback(
        []([[maybe_unused]] auto* widget, auto* user_data) {
            auto* weak_ptr =
                static_cast<std::weak_ptr<DupDetectWindow>*>(user_data);
            if (auto ui = weak_ptr->lock()) {
                ui->perform_remove_item();
            }
        },
        make_callback_data());

    w->My_deleteItemButton->callback(
        []([[maybe_unused]] Fl_Widget* widget, void* user_data) {
            auto* weak_ptr =
                static_cast<std::weak_ptr<DupDetectWindow>*>(user_data);
            if (auto ui = weak_ptr->lock()) {
                ui->perform_delete_item();
            }
        },
        make_callback_data());

    w->My_selectDirButton->callback(
        []([[maybe_unused]] Fl_Widget* widget, void* user_data) {
            auto* weak_ptr =
                static_cast<std::weak_ptr<DupDetectWindow>*>(user_data);
            if (auto ui = weak_ptr->lock()) {
                ui->perform_choose_dir();
            }
        },
        make_callback_data());

    w->My_startScanButton->callback(
        []([[maybe_unused]] Fl_Widget* widget, void* user_data) {
            auto* weak_ptr =
                static_cast<std::weak_ptr<DupDetectWindow>*>(user_data);
            if (auto ui = weak_ptr->lock()) {
                ui->perform_start_scan();
            }
        },
        make_callback_data());

    return w;
}
