// generated by Fast Light User Interface Designer (fluid) version 1.0404

#include "MainUI.hpp"

#include <iostream>
#include <thread>
#include "FL/Fl_Native_File_Chooser.H"

#include "fileutils.hpp"
#include "fllock.hpp"

DupDetectWindow::DupDetectWindow(int w, int h) : Fl_Window(w, h)
{
}
DupDetectWindow::~DupDetectWindow() = default;

void DupDetectWindow::updateTable(
    std::map<std::string, std::vector<std::string>>& duplicateFiles)
{
    auto progressBar = My_scanProgressBar;
    My_resultsTree->clear();
    std::cout << "Updating results table..." << std::endl;
    auto amount = duplicateFiles.size();
    int  count  = 0;
    {
        FLLock l;
        progressBar->value(0);
        progressBar->minimum(0);
        progressBar->maximum(amount);
    }
    std::cout << "Total unique hashes: " << amount << std::endl;
    for (const auto& [hash, files] : duplicateFiles) {
        std::cout << "Processing hash: " << hash << " with " << files.size()
                  << " files." << std::endl;
        if (files.size() > 1) {
            auto text = "Hash: " + hash + " (" + std::to_string(files.size()) +
                        " files)";
            std::cout << "Adding tree parent: " << text << std::endl;
            auto parent = My_resultsTree->add(text.c_str());
            {
                FLLock l;
                for (const auto& file : files) {
                    My_resultsTree->add(parent, file.c_str());
                }
            }
        }
        {
            FLLock l;
            progressBar->value(++count);
        }
    }
    std::cout << "Results table update complete." << std::endl;
    My_resultsTree->redraw();
}

DupDetectWindow* DupDetectWindow::create()
{
    DupDetectWindow* w;
    {
        auto* o = new DupDetectWindow(770, 507);
        w       = o;
        (void) w;
        o->box(FL_FLAT_BOX);
        o->color(FL_BACKGROUND_COLOR);
        o->selection_color(FL_BACKGROUND_COLOR);
        o->labeltype(FL_NO_LABEL);
        o->labelfont(0);
        o->labelsize(14);
        o->labelcolor(FL_FOREGROUND_COLOR);
        o->align(Fl_Align(FL_ALIGN_TOP));
        o->when(FL_WHEN_RELEASE);
        {
            Fl_Button* o = new Fl_Button(15, 15, 132, 28, "Choose Directory");
            o->tooltip("Choose a directory to scan for duplicates");
            o->selection_color((Fl_Color) 48);
            o->align(Fl_Align(FL_ALIGN_WRAP));
            w->My_selectDirButton = o;
        }  // Fl_Button* o
        {
            Fl_Output* o = new Fl_Output(229, 15, 443, 28, "Directory:");
            o->color((Fl_Color) 48);
            w->My_selectedDirOutput = o;
        }  // Fl_Output* o
        {
            w->My_startScanButton = new Fl_Button(685, 15, 70, 28, "Scan");
        }  // Fl_Button* o
        {
            w->My_scanProgressBar =
                new Fl_Progress(15, 107, 740, 24, "Scan Progress");
            w->My_scanProgressBar->minimum(0);
            w->My_scanProgressBar->maximum(100);
        }  // Fl_Progress* o
        {
#ifdef __APPLE__
            auto text_width = fl_width("Currently Hashing:");
#else
            auto text_width = 100;
#endif
            Fl_Output* o =
                new Fl_Output(text_width + 17, 61, 740 - 2 - text_width, 28,
                              "Currently Hashing:");
            o->color((Fl_Color) 48);
            w->My_currentTargetFile = o;
        }  // Fl_Output* o
        {
            w->My_resultsTree = new Fl_Tree(15, 153, 740, 339);
            w->resizable(w->My_resultsTree);
        }  // Fl_Tree* o
        o->end();
    }  // DupDetectWindow* o

    w->My_selectDirButton->callback(
        []([[maybe_unused]] Fl_Widget* w, void* data) {
            auto* ui = static_cast<DupDetectWindow*>(data);
            // Callback code for My_selectDirButton
            Fl_Native_File_Chooser fc;
            fc.title("Select Directory to Scan");
            fc.type(Fl_Native_File_Chooser::BROWSE_DIRECTORY);
            fc.show();
            ui->My_selectedDirOutput->value(fc.filename());
        },
        w);

    w->My_startScanButton->callback(
        []([[maybe_unused]] Fl_Widget* w, void* data) {
            auto*       ui          = static_cast<DupDetectWindow*>(data);
            std::string selectedDir = ui->My_selectedDirOutput->value();
            if (ui->My_selectedDirOutput->value()[0] == '\0') {
                std::cout << "No directory selected." << std::endl;
                fl_alert("No directory chosen!");
                return;
            }

            if (ui->scanning) {
                {
                    FLLock l;
                    ui->My_startScanButton->label("Scan");
                    ui->My_currentTargetFile->value("<none>");
                    ui->My_scanProgressBar->value(
                        ui->My_scanProgressBar->maximum());
                }
                ui->scanning = false;
                return;
            } else {
                ui->scanning = true;
                {
                    FLLock l;
                    ui->My_startScanButton->label("Cancel Scan");
                    ui->My_resultsTree->clear();
                }
                std::thread t{[ui, selectedDir]() {
                    DirectoryHasher hasher(selectedDir);
                    {
                        FLLock l;
                        ui->My_scanProgressBar->minimum(0);
                        ui->My_scanProgressBar->maximum(hasher.get_total());
                        ui->My_currentTargetFile->value(
                            (hasher.will_be_hashed().value_or("...")).c_str());
                    }
                    while (auto result = hasher.next()) {
                        std::cout << "Hashed: " << std::get<0>(*(result))
                                  << " -> " << std::get<1>(*(result))
                                  << std::endl;
                        if (!ui->scanning) {
                            break;
                        }
                        {
                            FLLock l;
                            ui->My_scanProgressBar->value(
                                hasher.get_progress());
                            ui->My_currentTargetFile->value(
                                (hasher.will_be_hashed().value_or("..."))
                                    .c_str());
                        }
                    }
                    ui->scanning = false;
                    std::cout << "Hashing complete. Unique hashes found: "
                              << hasher.duplicates.size() << std::endl;
                    ui->updateTable(hasher.duplicates);
                    {
                        FLLock l;
                        ui->My_startScanButton->label("Scan");
                        ui->My_scanProgressBar->value(0);
                        ui->My_currentTargetFile->value("<none>");
                    }
                }};
                t.detach();
            }
        },
        w);

    return w;
}
