// generated by Fast Light User Interface Designer (fluid) version 1.0404

#include "MainUI.hpp"
#include <FL/Enumerations.H>
#include <FL/fl_ask.H>
#include <FL/Fl_Text_Display.H>
#include <FL/Fl_Tree.H>
#include <FL/Fl_Tree_Item.H>
#include <FL/Fl_Widget.H>
#include <FL/Fl_Window.H>

#include <algorithm>
#include <atomic>
#include <cassert>
#include <cstring>
#include <format>
#include <iostream>
#include <memory>
#include <stdexcept>
#include <string>
#include <thread>
#include <unordered_set>
#include <utility>
#include "FL/Fl_Native_File_Chooser.H"

#include "file-platform.hpp"
#include "fileutils.hpp"
#include "scwindow.hpp"
#include "uiupdate.hpp"
#include "uiutils.hpp"
#include "utils.hpp"

auto center(Fl_Window *self, Fl_Window *parent, int w, int h) -> Fl_Window*
{
    auto max_x = parent == nullptr ? Fl::w() : parent->w();
    auto max_y = parent == nullptr ? Fl::h() : parent->h();

    auto px = parent == nullptr ? 0 : parent->x();
    auto py = parent == nullptr ? 0 : parent->y();

    auto x = px + (max_x / 2) - (w / 2);
    auto y = py + (max_y / 2) - (h / 2);

    self->resize(x, y, w, h);
    return self;
}

auto center(Fl_Window* self, Fl_Window* parent) -> Fl_Window*
{
    return center(self, parent, self->w(), self->h());
}

int* const DupDetectWindow::survivor_sentinel = new int(1);
int* const DupDetectWindow::parent_sentinel   = new int(2);

static void relabel_hash_parent(Fl_Tree_Item* item)
{
    if (!item || !item->label()) {
        ::output("Unexpected null item! Application will terminate!");
        die();
    }
    // re-make the label for this hash to reflect the removed files
    std::string label = item->label();
    auto        pos   = std::find(label.begin(), label.end(), '(');
    if (pos == label.end()) {
        ::output(
            "Hash parent relabel does not match expected string. Application "
            "will terminate!");
        die();
    }
    std::string prefix(label.begin(), pos);
    std::string result = std::format("{}({} files)", prefix, item->children());
    item->label(result.c_str());
}

std::shared_ptr<DupDetectWindow> DupDetectWindow::construct_window()
{
    auto w = std::shared_ptr<DupDetectWindow>{new DupDetectWindow(770, 580)};
    w->box(FL_FLAT_BOX);
    w->color(FL_BACKGROUND_COLOR);
    w->selection_color(FL_BACKGROUND_COLOR);
    w->labeltype(FL_NO_LABEL);
    w->labelfont(0);
    w->labelsize(14);
    w->labelcolor(FL_FOREGROUND_COLOR);
    w->align(Fl_Align(FL_ALIGN_TOP));
    w->when(FL_WHEN_RELEASE);
    {
        Fl_Button* o = new Fl_Button(15, 15, 132, 28, "Choose Directory");
        o->tooltip("Choose a directory to scan for duplicates");
        o->selection_color((Fl_Color) 48);
        o->align(Fl_Align(FL_ALIGN_WRAP));
        w->My_selectDirButton = o;
    }  // Fl_Button* o
    {
        Fl_Output* o = new Fl_Output(229, 15, 443, 28, "Directory:");
        o->color((Fl_Color) 48);
        w->My_selectedDirOutput = o;
    }  // Fl_Output* o
    {
        w->My_startScanButton = new Fl_Button(685, 15, 70, 28, "Scan");
        w->My_startScanButton->tooltip("Start scanning for duplicates");
        w->My_startScanButton->align(Fl_Align(FL_ALIGN_WRAP));
        w->My_startScanButton->deactivate();
    }  // Fl_Button* o
    {
        w->My_scanProgressBar =
            new Fl_Progress(15, 105, 740, 25, "Scan Progress");
        w->My_scanProgressBar->minimum(0);
        w->My_scanProgressBar->maximum(100);
    }  // Fl_Progress* o
    {
#ifdef __APPLE__
        // macOS allows us to call fl_width with no window, but linux does
        // not;
        auto text_width = fl_width("Currently Hashing:");
#else
        auto text_width = 125;
#endif
        Fl_Output* o = new Fl_Output(text_width + 17, 60, 740 - 2 - text_width,
                                     28, "Currently Hashing:");
        o->color((Fl_Color) 48);
        w->My_currentTargetFile = o;
    }  // Fl_Output* o
    {
        Fl_Output* o = new Fl_Output(20, 150, 740, 28);
        o->box(FL_NO_BOX);
        o->color(FL_GRAY);
        o->value(
            "Click a hash to delete all matching duplicates except the "
            "blue one. Click ANY file to delete it directly.");
    }
    {
        w->My_resultsTree = new Fl_Tree(15, 180, 740, 340);
        w->resizable(w->My_resultsTree);
    }  // Fl_Tree* o
    {
        w->My_deleteItemButton = new Fl_Button(15, 530, 132, 28, "Delete");
        w->My_deleteItemButton->deactivate();
    }
    {
        w->My_removeItemButton = new Fl_Button(157, 530, 132, 28, "Ignore");
        w->My_removeItemButton->deactivate();
    }
    {
        w->My_showItemButton = new Fl_Button(300, 530, 132, 28, "Reveal Item");
        w->My_showItemButton->deactivate();
    }
    w->end();
    return w;
}  // DupDetectWindow* o

DupDetectWindow::DupDetectWindow(int w, int h)
    : Fl_Window(w, h), survivor_strategy()
{
    center(this, nullptr);
}

DupDetectWindow::~DupDetectWindow() noexcept = default;

void DupDetectWindow::perform_choose_dir()
{
    Fl_Native_File_Chooser fc;
    fc.title("Select Directory to Scan");
    fc.type(Fl_Native_File_Chooser::BROWSE_DIRECTORY);
    fc.show();
    auto filename = fc.filename();
    My_selectedDirOutput->value(filename);
    if (filename && *filename) {
        My_startScanButton->activate();
    } else {
        My_startScanButton->deactivate();
    }
}

void DupDetectWindow::send_progress(std::shared_ptr<DupDetectWindow> window,
                                    std::size_t                      progress,
                                    std::size_t                      total,
                                    std::string const&               message)
{
    assert(window != nullptr);
    // this will be freed in the callback function
    UIUpdate* update = new UIUpdate();
    update->message  = message;
    update->window   = window;
    update->progress = progress;
    update->total    = total;
    update->type     = UIUpdate::Type::Progress;
    Fl::awake(ui_scan_update_cb, update);
}

void DupDetectWindow::send_done(
    std::shared_ptr<DupDetectWindow>            window,
    std::size_t                                 progress,
    std::size_t                                 total,
    std::string const&                          message,
    DupDetectWindow::DuplicateFilesCollection&& files)
{
    assert(window != nullptr);
    // this will be freed in the callback function
    UIUpdate* update = new UIUpdate();
    update->duplicates =
        std::make_shared<DupDetectWindow::DuplicateFilesCollection>(
            std::move(files));
    update->message  = message;
    update->window   = window;
    update->progress = progress;
    update->total    = total;
    update->type     = UIUpdate::Type::Done;
    window->scanning.store(false, std::memory_order_release);
    Fl::awake(ui_scan_update_cb, update);
}

void DupDetectWindow::perform_start_scan()
{
    std::string selectedDir = My_selectedDirOutput->value();
    if (selectedDir.empty()) {
        std::cout << "No directory selected." << std::endl;
        fl_alert("No directory chosen!");
        return;
    }

    if (scanning.load(std::memory_order_acquire)) {
        // if we are scanning and we click this button
        // we should cancel the scan and update the UI
        display_not_scanning();
        scanning.store(false, std::memory_order_release);
        return;
    } else {
        // if we are not scanning we will ask for a strategy
        // update the ui and spawn a thread to start the scan
        scanning.store(true, std::memory_order_release);
        if (!ask_for_choice()) {
            return;
        }

        My_startScanButton->label("Cancel Scan");
        My_resultsTree->clear();
        std::thread t{[win = this->shared_from_this(), selectedDir]() {
            // TODO: this can throw, we should probably check for that

            std::unique_ptr<DirectoryHasher> hasher;
            try {
                hasher = std::make_unique<DirectoryHasher>(selectedDir);
            } catch (std::exception& e) {
                fl_alert(
                    "Cannot access selected directory for hashing. Ensure "
                    "appropriate permissions or select a new directory!");
                win->send_done(win, 0, 0, "ERROR READING DIR",
                               DupDetectWindow::DuplicateFilesCollection{});
            }
            std::atomic<bool> update_ready{false};

            std::thread pt{[&hasher, win, &update_ready]() {
                while (win->scanning.load(std::memory_order_acquire)) {
                    std::this_thread::sleep_for(ui_update_delay);
                    if (update_ready.load()) {
                        win->send_progress(
                            win, hasher->get_progress(), hasher->get_total(),
                            hasher->will_be_hashed().value_or("..."));
                        update_ready.store(false);
                    }
                }
            }};

            while (auto result = hasher->next()) {
                update_ready.store(true);
                debug_output("Hashed: ", std::get<0>(*(result)), " -> ",
                             std::get<1>(*(result)));
                // check to see if the user has cancelled
                // if so, stop, update the ui, and end the thread
                if (!win->scanning.load(std::memory_order::acquire)) {
                    break;
                }
            }
            win->send_done(win, hasher->get_progress(), hasher->get_total(),
                           "<none>", std::move(hasher->duplicates));
            // pt must be after send_done because send_done sets scanning to
            // false breaking out of hte pt loop
            pt.join();
            debug_output("Hashing complete. Unique hashes found: ",
                         hasher->duplicates.size());
        }};
        t.detach();
    }
}

static Fl_Tree_Item* try_get_selected_item(Fl_Tree* tree)
{
    auto* item = tree->first_selected_item();
    if (item == nullptr) {
        fl_alert("No selection");
        return nullptr;
    }

    if (item == tree->root()) {
        fl_alert(
            "Cannot delete the root element. Choose a hash or an "
            "individual file");
        return nullptr;
    }
    return item;
}

void DupDetectWindow::perform_show_item()
{
    auto* item = My_resultsTree->first_selected_item();

    if (item == nullptr) {
        fl_alert("No selection!");
        return;
    }

    if (item->user_data() == parent_sentinel ||
        item == My_resultsTree->root()) {
        fl_alert("Select a single file to reveal it");
        return;
    }

    reveal_file(item->label());
}

void DupDetectWindow::perform_delete_item()
{
    Fl_Tree_Item* item = try_get_selected_item(My_resultsTree);
    if (item == nullptr) {
        return;
    }

    // check != parent_sentintel bc a child can have nullptr OR
    // survivor_sentinel for user_data
    if (item->user_data() != parent_sentinel) {
        // delete a single file
        // ask for confirmation
        auto result =
            confirm("Are you sure you want to delete %s.", item->label());
        if (result != ConfirmResult::YES) {
            return;
        }
        // this is a specific file that the user chose to delete
        ::output("Deleting specific file ", item->label());

        delete_single_item(item);
    } else {
        // Delete all duplicates
        // confirm with the user first
        auto child_count = item->children();
        if (child_count == 0) {
            fl_alert("Nothing to delete!");
            return;
        }

        if (child_count == 1) {
            fl_alert(
                "There exists ONLY ONE file matching this hash left. "
                "To delete it, select it and delete it explicitly");
            return;
        }

        auto result = confirm(
            "Warning you are about to delete %d files. ALL "
            "files under this hash except the newest will be "
            "deleted. Do you want to continue?",
            child_count - 1);

        if (result != ConfirmResult::YES) {
            return;
        }

        ::output("Will delete all duplicates except designated survivor");
        delete_hash_parent_item(item, child_count);
    }
    // TODO: why does the UI not refresh even if I call Fl::check();
}

void DupDetectWindow::perform_remove_item()
{
    auto*               item = My_resultsTree->first_selected_item();
    static ConfirmToken remove_token{};

    if (item == nullptr) {
        fl_alert("No selection!");
        return;
    }

    if (item->user_data() == parent_sentinel) {
        // we have a parent

        // double check with the user
        auto result = confirm(
            &remove_token, "Are you sure you want to hide %s?", item->label());
        if (result != ConfirmResult::YES) {
            return;
        }

        // lets not show it but not actually do anything
        My_resultsTree->remove(item);
        return;
    }
    fl_alert("Can only ignore hash values. Select a hash to ignore it.");
}

void DupDetectWindow::delete_single_item(Fl_Tree_Item* item)
{
    // Fix parent content to reflect removed file
    auto* parent = item->parent();
    if (parent == nullptr) {
        ::output("Unexpected nullptr parent on ", item->label());
        throw std::runtime_error("unexpected null parent");
    }

    if (item->user_data() == survivor_sentinel && parent->children() > 1) {
        // item is designated survivor, new survivor must be chosen
        // AS LONG AS there are still other files to choose from
        // If this is the last file matching the hash, it can be
        // removed//
        choose_survivor_after_delete(parent, item);
    }

    My_resultsTree->remove(item);
    // TODO: actual file deleting :grimace:

    // if there are files left, reflect that in the count in the
    // parent otherwise remove the empty hash from the view since it
    // is empty
    if (parent->children() > 0) {
        relabel_hash_parent(parent);
    } else {
        My_resultsTree->remove(parent);
    }
}

void DupDetectWindow::delete_hash_parent_item(Fl_Tree_Item* item,
                                              int           child_count)
{
    // find the child with the user data indicating it is
    // the newest and should be saved
    for (auto i = child_count - 1; i >= 0; --i) {
        if (auto* child = item->child(i);
            child && child->user_data() != survivor_sentinel) {
            ::output("Will delete ", child->label());
            My_resultsTree->remove(child);
            // TODO: delete actual files
        }
    }

    relabel_hash_parent(item);
}

bool DupDetectWindow::ask_for_choice()
{
    auto choicer = std::make_unique<SurvivorChoiceWindow>(this);
    center(choicer.get(), this);
    choicer->show_and_wait();

    if (choicer->was_cancelled()) {
        fl_alert("No selection made. Cancelling scan");
        return false;
    }

    survivor_strategy = choicer->get_choice();
    return true;
}

std::string DupDetectWindow::choose_survivor_after_delete(
    Fl_Tree_Item* parent,
    Fl_Tree_Item* old_survivor)
{
    std::vector<std::string> options{};
    for (int i = parent->children() - 1; i >= 0; --i) {
        auto* child = parent->child(i);
        if (child == old_survivor)
            continue;
        options.emplace_back(child->label());
    }

    auto new_survivor = choose_survivor(options);

    auto* new_child_survivor = parent->find_child_item(new_survivor.data());
    if (new_child_survivor == nullptr) {
        fl_alert(
            "Could not find suitable replacement for deleted survivor. Program "
            "will terminate!");
        die();
    }
    new_child_survivor->user_data(survivor_sentinel);
    new_child_survivor->labelfgcolor(FL_BLUE);
    old_survivor->user_data(nullptr);
    return new_survivor;
}

std::string DupDetectWindow::choose_survivor(
    std::vector<std::string> const& files) const
{
    if (files.empty()) {
        std::cerr << "Cannot choose survivor from set of 0 options"
                  << std::endl;
        fl_alert(
            "Cannot choose survivor from 0 options. Program will terminate!");
        die();
    }

    switch (survivor_strategy) {
        case SurvivorChoiceType::RANDOM:
            // simulate randomness for debugging purposes
            return files.front();
        case SurvivorChoiceType::NEWEST:
            return *std::max_element(std::begin(files), std::end(files),
                                     [](auto const& file1, auto const& file2) {
                                         return last_write_time_safe(file1) <
                                                last_write_time_safe(file2);
                                     });
        case SurvivorChoiceType::OLDEST:
            return *std::min_element(std::begin(files), std::end(files),
                                     [](auto const& file1, auto const& file2) {
                                         return last_write_time_safe(file1) <
                                                last_write_time_safe(file2);
                                     });
    }

    fl_alert("Invalid choice. Program will terminate!");
    die();
    // let's hope so anyway
    std::unreachable();
}

void DupDetectWindow::updateTable(
    std::unordered_map<HashType, std::vector<PathType>> const& duplicateFiles)
{
    auto progressBar = My_scanProgressBar;
    My_resultsTree->clear();
    debug_output("Updating results table...");
    auto amount = duplicateFiles.size();

    if (amount == 0) {
        ::output("NO DUPLICATES FOUND");
        My_resultsTree->add("No duplicates found!");
        My_deleteItemButton->deactivate();
        My_removeItemButton->deactivate();
        My_showItemButton->deactivate();
        return;
    } else {
        My_deleteItemButton->activate();
        My_removeItemButton->activate();
        My_showItemButton->activate();
    }

    int count = 0;
    reset_progress(0, amount);
    progressBar->value(amount);
    debug_output("Total unique hashes: ", amount);
    for (const auto& [hash, files] : duplicateFiles) {
        debug_output("Processing hash: ", hash, " with ", files.size(),
                     " files.");
        if (files.size() > 1) {
            auto text = "Hash: " + hash + " (" + std::to_string(files.size()) +
                        " files)";
            debug_output("Adding tree parent: ", text);
            auto parent = My_resultsTree->add(text.c_str());
            parent->user_data(parent_sentinel);
            auto survivor = choose_survivor(files);
            for (const auto& file : files) {
                auto* item = My_resultsTree->add(parent, file.c_str());
                item->labelfgcolor(FL_GRAY);
            }
            auto* sur = parent->find_child_item(survivor.data());
            sur->user_data(survivor_sentinel);
            sur->labelfgcolor(FL_BLUE);
        }
        progressBar->value(++count);
    }
    debug_output("Results table update complete.");
    My_resultsTree->redraw();
}

void DupDetectWindow::display_not_scanning()
{
    My_startScanButton->label("Scan");
    My_currentTargetFile->value("<none>");
    My_scanProgressBar->value(My_scanProgressBar->maximum());
}

void DupDetectWindow::reset_progress(int min, int max)
{
    My_scanProgressBar->minimum(min);
    My_scanProgressBar->maximum(max);
    My_scanProgressBar->value(min);
}

/* The caller of create() MUST keep the shared_ptr alive for the duration of the
 * program Callbacks used by Fl::awake call shared_from_this() on the raw
 * pointer to DupDetectWindow. If the window is destroyed or invalidated before
 * the end the program, these callbacks can reference bad memory. */
std::shared_ptr<DupDetectWindow> DupDetectWindow::create()
{
    std::shared_ptr<DupDetectWindow> w = construct_window();

    w->My_showItemButton->callback(
        []([[maybe_unused]] auto* widget, auto* win) {
            auto ui = static_cast<DupDetectWindow*>(win)->shared_from_this();
            ui->perform_show_item();
        },
        w.get());

    w->My_removeItemButton->callback(
        []([[maybe_unused]] auto* widget, auto* win) {
            auto ui = static_cast<DupDetectWindow*>(win)->shared_from_this();
            ui->perform_remove_item();
        },
        w.get());

    w->My_deleteItemButton->callback(
        []([[maybe_unused]] Fl_Widget* w, void* data) {
            auto ui = static_cast<DupDetectWindow*>(data)->shared_from_this();
            ui->perform_delete_item();
        },
        w.get());

    w->My_selectDirButton->callback(
        []([[maybe_unused]] Fl_Widget* w, void* data) {
            auto ui = static_cast<DupDetectWindow*>(data)->shared_from_this();
            // Callback code for My_selectDirButton
            ui->perform_choose_dir();
        },
        w.get());

    w->My_startScanButton->callback(
        []([[maybe_unused]] Fl_Widget* w, void* data) {
            auto ui = static_cast<DupDetectWindow*>(data)->shared_from_this();
            ui->perform_start_scan();
        },
        w.get());

    return w;
}
