// generated by Fast Light User Interface Designer (fluid) version 1.0404

#ifndef MainUI_h
#define MainUI_h
#include <FL/Fl.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_Output.H>
#include <FL/Fl_Progress.H>
#include <FL/Fl_Tree.H>
#include <FL/Fl_Window.H>
#include <string>
#include <unordered_map>
#include <vector>
#include "fileutils.hpp"

class DupDetectWindow : public Fl_Window {
   public:
    using HashType = DirectoryHasher::HashType;
    using PathType = DirectoryHasher::PathType;

   private:
    Fl_Button*   My_selectDirButton{};
    Fl_Button*   My_startScanButton{};
    Fl_Button*   My_cancelScanButton{};
    Fl_Output*   My_selectedDirOutput{};
    Fl_Output*   My_currentTargetFile{};
    Fl_Progress* My_scanProgressBar{};
    Fl_Button*   My_deleteItemButton{};
    Fl_Tree*     My_resultsTree{};
    bool         scanning{false};

    void updateTable(
        std::unordered_map<HashType, std::vector<PathType>>& duplicateFiles);

   public:
    DupDetectWindow(int w, int h);
    ~DupDetectWindow() override;

    static DupDetectWindow* create();
};

#endif
