// generated by Fast Light User Interface Designer (fluid) version 1.0404

#ifndef MainUI_h
#define MainUI_h
#include <FL/Fl.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_Output.H>
#include <FL/Fl_Progress.H>
#include <FL/Fl_Tree.H>
#include <FL/Fl_Window.H>
#include <map>
#include <string>
#include <vector>

class DupDetectWindow : public Fl_Window {
   private:
    Fl_Button*   My_selectDirButton{};
    Fl_Button*   My_startScanButton{};
    Fl_Button*   My_cancelScanButton{};
    Fl_Output*   My_selectedDirOutput{};
    Fl_Output*   My_currentTargetFile{};
    Fl_Progress* My_scanProgressBar{};
    Fl_Tree*     My_resultsTree{};
    bool         scanning{false};

    void updateTable(
        std::map<std::string, std::vector<std::string>>& duplicateFiles);

   public:
    DupDetectWindow(int w, int h);
    ~DupDetectWindow() override;

    static DupDetectWindow* create();
};

#endif
