// generated by Fast Light User Interface Designer (fluid) version 1.0404

#include "MainUI.hpp"
#include <FL/Enumerations.H>
#include <FL/Fl_Window.H>
#include <FL/fl_ask.H>
#include <FL/Fl_Tree_Item.H>
#include <FL/Fl_Widget.H>

#include <algorithm>
#include <cassert>
#include <cmath>
#include <cstring>
#include <filesystem>
#include <iostream>
#include <memory>
#include <stdexcept>
#include <string>
#include <thread>
#include <utility>
#include "FL/Fl_Native_File_Chooser.H"

#include "fileutils.hpp"
#include "fllock.hpp"
#include "uiutils.hpp"
#include "utils.hpp"

int* const DupDetectWindow::survivor_sentinel = new int(1);
int* const DupDetectWindow::parent_sentinel   = new int(2);

DupDetectWindow::DupDetectWindow(int w, int h) : Fl_Window(w, h)
{
}

DupDetectWindow::~DupDetectWindow() noexcept {
    Fl_Window::~Fl_Window();
}

bool DupDetectWindow::ask_for_choice()
{
    auto choicer = std::make_unique<SurvivorChoiceWindow>(this);
    choicer->show();

    if (choicer->was_cancelled()) {
        fl_alert("No selection made. Cancelling scan");
        return false;
    }

    choice = choicer->get_choice();
    return true;
}

std::string DupDetectWindow::choose_survivor_after_delete(
    Fl_Tree_Item* parent,
    Fl_Tree_Item* old_survivor)
{
    std::vector<std::string> options{};
    for (int i = parent->children() - 1; i >= 0; --i) {
        auto* child = parent->child(i);
        if (child == old_survivor)
            continue;
        options.emplace_back(child->label());
    }

    auto new_survivor = choose_survivor(options);

    auto* new_child_survivor = parent->find_child_item(new_survivor.data());
    if (new_child_survivor == nullptr) {
        fl_alert(
            "Could not find suitable replacement for deleted survivor. Program "
            "will terminate!");
        std::terminate();
    }
    new_child_survivor->user_data(survivor_sentinel);
    new_child_survivor->labelfgcolor(FL_BLUE);
    old_survivor->user_data(nullptr);
    return new_survivor;
}

std::string DupDetectWindow::choose_survivor(
    std::vector<std::string> const& files) const
{
    if (files.empty()) {
        std::cerr << "Cannot choose survivor from set of 0 options"
                  << std::endl;
        fl_alert(
            "Cannot choose survivor from 0 options. Program will terminate!");
        std::terminate();
    }
    if (choice == SurvivorChoiceType::RANDOM) {
        // simulate randomness for debugging purposes
        return files.front();
    } else if (choice == SurvivorChoiceType::NEWEST) {
        return *std::max_element(
            std::begin(files), std::end(files),
            [](auto const& file1, auto const& file2) {
                return std::filesystem::last_write_time(file1) <
                       std::filesystem::last_write_time(file2);
            });
    } else if (choice == SurvivorChoiceType::OLDEST) {
        return *std::min_element(
            std::begin(files), std::end(files),
            [](auto const& file1, auto const& file2) {
                return std::filesystem::last_write_time(file1) <
                       std::filesystem::last_write_time(file2);
            });
    }

    fl_alert("Invalid choice. Program will terminate!");
    std::terminate();
    // let's hope so anyay
    std::unreachable();
}

void DupDetectWindow::updateTable(
    std::unordered_map<HashType, std::vector<PathType>>& duplicateFiles)
{
    auto progressBar = My_scanProgressBar;
    My_resultsTree->clear();
    ::output("Updating results table...");
    auto amount = duplicateFiles.size();
    int  count  = 0;
    {
        FLLock l;
        progressBar->value(0);
        progressBar->minimum(0);
        progressBar->maximum(amount);
    }
    ::output("Total unique hashes: ", amount);
    for (const auto& [hash, files] : duplicateFiles) {
        ::output("Processing hash: ", hash, " with ", files.size(), " files.");
        if (files.size() > 1) {
            auto text = "Hash: " + hash + " (" + std::to_string(files.size()) +
                        " files)";
            ::output("Adding tree parent: ", text);
            {
                FLLock l;
                auto   parent = My_resultsTree->add(text.c_str());
                parent->user_data(parent_sentinel);
                auto survivor = choose_survivor(files);
                for (const auto& file : files) {
                    auto* item = My_resultsTree->add(parent, file.c_str());
                    item->labelfgcolor(FL_GRAY);
                }
                auto* sur = parent->find_child_item(survivor.data());
                sur->user_data(survivor_sentinel);
                sur->labelfgcolor(FL_BLUE);
            }
        }
        {
            FLLock l;
            progressBar->value(++count);
        }
    }
    ::output("Results table update complete.");
    My_resultsTree->redraw();
}

static inline void relabel_hash_parent(Fl_Tree_Item* item)
{
    // re-make the label for this hash to reflect the removed files
    // 'Hash: ' + hash length + ' ' + (n item) + \0
    int   digits = item->children() == 0 ? 1 : std::log10(item->children()) + 1;
    int   len    = 6 + 64 + 1 + digits + 9 + 1;
    char* new_label = new char[len];
    std::memcpy(new_label, item->label(), 6 + 64);
    snprintf(new_label + 64 + 6, digits + 10, " (%d files)", item->children());
    new_label[len - 1] = 0;

    item->label(new_label);
}

void DupDetectWindow::display_not_scanning()
{
    My_startScanButton->label("Scan");
    My_currentTargetFile->value("<none>");
    My_scanProgressBar->value(My_scanProgressBar->maximum());
}

void DupDetectWindow::reset_progress(int min, int max)
{
    My_scanProgressBar->minimum(min);
    My_scanProgressBar->maximum(max);
    My_scanProgressBar->value(min);
}

DupDetectWindow* DupDetectWindow::create()
{
    DupDetectWindow* w;
    {
        auto *o = new DupDetectWindow(770, 565);
        (void) w;
        o->box(FL_FLAT_BOX);
        o->color(FL_BACKGROUND_COLOR);
        o->selection_color(FL_BACKGROUND_COLOR);
        o->labeltype(FL_NO_LABEL);
        o->labelfont(0);
        o->labelsize(14);
        o->labelcolor(FL_FOREGROUND_COLOR);
        o->align(Fl_Align(FL_ALIGN_TOP));
        o->when(FL_WHEN_RELEASE);
        w       = std::move(o);
        {
            Fl_Button* o = new Fl_Button(15, 15, 132, 28, "Choose Directory");
            o->tooltip("Choose a directory to scan for duplicates");
            o->selection_color((Fl_Color) 48);
            o->align(Fl_Align(FL_ALIGN_WRAP));
            w->My_selectDirButton = o;
        }  // Fl_Button* o
        {
            Fl_Output* o = new Fl_Output(229, 15, 443, 28, "Directory:");
            o->color((Fl_Color) 48);
            w->My_selectedDirOutput = o;
        }  // Fl_Output* o
        {
            w->My_startScanButton = new Fl_Button(685, 15, 70, 28, "Scan");
        }  // Fl_Button* o
        {
            w->My_scanProgressBar =
                new Fl_Progress(15, 107, 740, 24, "Scan Progress");
            w->My_scanProgressBar->minimum(0);
            w->My_scanProgressBar->maximum(100);
        }  // Fl_Progress* o
        {
#ifdef __APPLE__
            // macOS allows us to call fl_width with no window, but linux does
            // not;
            auto text_width = fl_width("Currently Hashing:");
#else
            auto text_width = 125;
#endif
            Fl_Output* o =
                new Fl_Output(text_width + 17, 61, 740 - 2 - text_width, 28,
                              "Currently Hashing:");
            o->color((Fl_Color) 48);
            w->My_currentTargetFile = o;
        }  // Fl_Output* o
        {
            w->My_resultsTree = new Fl_Tree(15, 153, 740, 339);
            w->resizable(w->My_resultsTree);
        }  // Fl_Tree* o
        {
            w->My_deleteItemButton =
                new Fl_Button(15, 510, 132, 28, "Delete Duplicates");
        }
        {
            w->My_removeItemButton =
                new Fl_Button(157, 510, 132, 28, "Ignore Entry");
        }
        o->end();
    }  // DupDetectWindow* o

    w->My_removeItemButton->callback(
        []([[maybe_unused]] auto* widget, auto* win) {
            auto* ui   = static_cast<DupDetectWindow*>(win);
            auto* item = ui->My_resultsTree->first_selected_item();

            if (item == nullptr) {
                fl_alert("No selection!");
                return ;
            }
            
            if (item->user_data() == parent_sentinel) {
                // we have a parent
                // lets not show it but not actually do anything
                ui->My_resultsTree->remove(item);
                return;
            }
            fl_alert(
                "Can only ignore hash values. Select a hash to ignore it.");
        },
        w);

    w->My_deleteItemButton->callback(
        []([[maybe_unused]] Fl_Widget* w, void* data) {
            auto* ui   = static_cast<DupDetectWindow*>(data);
            auto* item = ui->My_resultsTree->first_selected_item();
            if (item == nullptr) {
                fl_alert("No selection");
                return ;
            }
            ::output(item->label());
            // check != parent_sentintel bc a child can have nullptr OR
            // survivor_sentinel for user_data
            if (item->user_data() != parent_sentinel) {
                // delete a single file
                // ask for confirmation
                auto result = confirm("Are you sure you want to delete %s.",
                                      item->label());
                if (result != ConfirmResult::YES) {
                    return;
                }
                // this is a specific file that the user chose to delete
                ::output("Deleting specific file ", item->label());

                // Fix parent content to reflect removed file
                auto* parent = item->parent();
                if (parent == nullptr) {
                    ::output("Unexpected nullptr parent on ", item->label());
                    throw std::runtime_error("unexpected null parent");
                }

                if (item->user_data() == survivor_sentinel &&
                    parent->children() > 1) {
                    // item is designated survivor, new survivor must be chosen
                    // AS LONG AS there are still other files to choose from
                    // If this is the last file matching the hash, it can be
                    // removed//
                    ui->choose_survivor_after_delete(parent, item);
                }

                ui->My_resultsTree->remove(item);
                // TODO: actual file deleting :grimace:
                relabel_hash_parent(parent);
            } else {
                // Delete all duplicates
                // confirm with the user first
                auto child_count = item->children();
                if (child_count == 0) {
                    fl_alert("Nothing to delete!");
                    return;
                }

                if (child_count == 1) {
                    fl_alert(
                        "There exists ONLY ONE file matching this hash left. "
                        "To delete it, select it and delete it explicitly");
                    return;
                }

                auto result = confirm(
                    "Warning you are about to delete %d files. ALL "
                    "files under this hash except the newest will be "
                    "deleted. Do you want to continue?",
                    child_count - 1);
                if (result != ConfirmResult::YES) {
                    return;
                }
                ::output("Will delete all duplicates except newest");
                // find the child with the user data indicating it is
                // the newest and should be saved
                for (auto i = child_count - 1; i >= 0; --i) {
                    auto* child = item->child(i);
                    if (child->user_data() != survivor_sentinel) {
                        ::output("Will delete ", child->label());
                        ui->My_resultsTree->remove(child);
                        // TODO: delete actual files
                    }
                }

                relabel_hash_parent(item);
            }
            // TODO: why does the UI not refresh even if I call
            // Fl::check();
        },
        w);

    w->My_selectDirButton->callback(
        []([[maybe_unused]] Fl_Widget* w, void* data) {
            auto* ui = static_cast<DupDetectWindow*>(data);
            // Callback code for My_selectDirButton
            Fl_Native_File_Chooser fc;
            fc.title("Select Directory to Scan");
            fc.type(Fl_Native_File_Chooser::BROWSE_DIRECTORY);
            fc.show();
            ui->My_selectedDirOutput->value(fc.filename());
        },
        w);

    w->My_startScanButton->callback(
        []([[maybe_unused]] Fl_Widget* w, void* data) {
            auto*       ui          = static_cast<DupDetectWindow*>(data);
            std::string selectedDir = ui->My_selectedDirOutput->value();
            if (ui->My_selectedDirOutput->value()[0] == '\0') {
                std::cout << "No directory selected." << std::endl;
                fl_alert("No directory chosen!");
                return;
            }

            if (ui->scanning) {
                // if we are scanning and we click this button
                // we should cancel the scan and update the UI
                {
                    FLLock l;
                    ui->display_not_scanning();
                }
                ui->scanning = false;
                return;
            } else {
                // if we are not scanning we will ask for a strategy
                // update the ui and spawn a thread to start the scan
                ui->scanning = true;

                if (!ui->ask_for_choice()) {
                    return;
                }

                {
                    FLLock l;
                    ui->My_startScanButton->label("Cancel Scan");
                    ui->My_resultsTree->clear();
                }
                std::thread t{[ui, selectedDir]() {
                    DirectoryHasher hasher(selectedDir);
                    {
                        FLLock l;
                        ui->reset_progress(0, hasher.get_total());
                        ui->My_currentTargetFile->value(
                            (hasher.will_be_hashed().value_or("...")).c_str());
                    }
                    while (auto result = hasher.next()) {
                        ::output("Hashed: ", std::get<0>(*(result)), " -> ",
                                 std::get<1>(*(result)));
                        // check to see if the user has cancelled
                        // if so, stop, update the ui, and end the thread
                        if (!ui->scanning) {
                            break;
                        }
                        {
                            FLLock l;
                            ui->My_scanProgressBar->value(
                                hasher.get_progress());
                            ui->My_currentTargetFile->value(
                                (hasher.will_be_hashed().value_or("..."))
                                    .c_str());
                        }
                    }
                    ui->scanning = false;
                    ::output("Hashing complete. Unique hashes found: ",
                             hasher.duplicates.size());
                    ui->updateTable(hasher.duplicates);
                    {
                        FLLock l;
                        ui->display_not_scanning();
                        ui->reset_progress(0, 1);
                    }
                }};
                t.detach();
            }
        },
        w);

    return w;
}
