// generated by Fast Light User Interface Designer (fluid) version 1.0404

#ifndef dupdetectwindow_h
#define dupdetectwindow_h
#include <atomic>
#include <memory>
#include <optional>
#include <thread>
#ifdef WIN32

#pragma comment(lib, "Gdiplus.lib")  // This can be used in Visual Studio, but
                                     // CMake handles linking
#pragma comment(lib, "Ws2_32.lib")
#pragma comment(lib, "comctl32.lib")

#endif

#include <FL/Fl.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_Menu_Item.H>
#include <FL/Fl_Output.H>
#include <FL/Fl_Progress.H>
#include <FL/Fl_Tree.H>
#include <FL/Fl_Tree_Item.H>
#include <FL/Fl_Window.H>
#include <string>
#include <unordered_map>
#include <vector>
#include "components/mytree.hpp"
#include "files/directoryhasher.hpp"
#include "scwindow.hpp"

class DupDetectWindow :
    public Fl_Window,
    public std::enable_shared_from_this<DupDetectWindow> {
   public:
    using HashType = DirectoryHasher::HashType;
    using PathType = DirectoryHasher::PathType;
    using DuplicateFilesCollection =
        std::unordered_map<HashType, HashEntry<PathType, HashType>>;

    friend void ui_scan_update_cb(void* data);

    constexpr static std::chrono::milliseconds ui_update_delay{25};

   private:
    SurvivorChoiceType survivor_strategy;

    Fl_Button*        My_selectDirButton{};
    Fl_Button*        My_startScanButton{};
    Fl_Button*        My_cancelScanButton{};
    Fl_Output*        My_selectedDirOutput{};
    Fl_Output*        My_currentTargetFile{};
    Fl_Progress*      My_scanProgressBar{};
    Fl_Button*        My_deleteItemButton{};
    Fl_Button*        My_removeItemButton{};
    Fl_Button*        My_showItemButton{};
    MyTree*           My_resultsTree{};
    std::atomic<bool> scanning{false};

    // Storage for weak_ptrs used in callbacks to prevent dangling pointer
    // issues
    std::vector<std::unique_ptr<std::weak_ptr<DupDetectWindow>>>
        callback_weakptrs_;

    // Scanning thread - stored so we can join it on destruction
    std::optional<std::thread> scan_thread_;

    // all button callbacks are prefixed with perform_
    void perform_choose_dir();

    void perform_start_scan();

    void perform_remove_item();

    void perform_show_item();

    void perform_delete_item();
    // methods not starting with perform_ are helper methods

    void send_progress(std::shared_ptr<DupDetectWindow> window,
                       std::size_t                      progress,
                       std::size_t                      total,
                       std::string const&               message);

    void send_done(std::shared_ptr<DupDetectWindow>          window,
                   std::size_t                               progress,
                   std::size_t                               total,
                   std::string const&                        message,
                   std::shared_ptr<DuplicateFilesCollection> files);

    void delete_single_item(MyTreeItem* item);

    void delete_hash_parent_item(MyTreeItem* item, int child_count);

    void update_table(std::shared_ptr<DuplicateFilesCollection> duplicateFiles);

    void display_not_scanning();

    void reset_progress(int min, int max);

    [[nodiscard]] std::string choose_survivor(
        std::vector<std::string> const& files) const;

    std::string choose_survivor_after_delete(MyTreeItem* parent,
                                             MyTreeItem* old_survivor);

    [[nodiscard]] bool ask_for_choice();

    [[nodiscard]] static std::shared_ptr<DupDetectWindow> construct_window();

   public:
    DupDetectWindow(int w, int h);
    ~DupDetectWindow() noexcept override;

    std::shared_ptr<DupDetectWindow::DuplicateFilesCollection> duplicates;

    [[nodiscard]] static std::shared_ptr<DupDetectWindow> create();
};

#endif
